theme: jekyll-theme-slate
title: Welcome to Tall1n's Blog!=!
description: With a background in economics and a professional focus on statistics and programming, this blog is about a wide range of topics. I am not sure yet what exactly I will write about, but a lack of ideas is, as usual, not the problem :)
