theme: jekyll-theme-slate
title: Welcome to Tall1n's Blog!=!
description: With a background in economics and a professional focus on statistics and programming, this blog is about a wide range of topics.
